from django.urls import path
from . import views

urlpatterns = [
    path("", views.inicio, name="inicio"),
    path("categorias/", views.lista_productos, name="categorias"),
    path("promociones/", views.promociones, name="promociones"),
    path("producto/<int:pk>/", views.detalle_producto, name="detalle_producto"),
    path("carrito/", views.ver_carrito, name="ver_carrito"),
    path("carrito/agregar/<int:pk>/", views.agregar_carrito, name="agregar_carrito"),
    path("carrito/eliminar/<int:pk>/", views.eliminar_carrito, name="eliminar_carrito"),
    path("login/", views.iniciar_sesion, name="login"),
    path("registro/", views.registrarse, name="registro"),
    path("logout/", views.cerrar_sesion, name="logout"),
    path("perfil/", views.perfil, name="perfil"),
    path("contacto/", views.contacto, name="contacto"),
    path("pago/", views.pago, name="pago"),
    path("confirmacion/", views.confirmacion, name="confirmacion"),
    path("panel/", views.panel, name="panel"),
    path("deseos/", views.lista_deseos, name="lista_deseos"),
    path("deseos/agregar/<int:pk>/", views.agregar_deseos, name="agregar_deseos"),
    path("deseos/eliminar/<int:pk>/", views.eliminar_deseos, name="eliminar_deseos"),
    path("mis-pedidos/", views.mis_pedidos, name="mis_pedidos"),
    path("cambiar-contrasena/", views.cambiar_contrasena, name="cambiar_contrasena"),
    path("direcciones/", views.direcciones_envio, name="direcciones_envio"),
    path("direcciones/agregar/", views.agregar_direccion, name="agregar_direccion"),
    path("direcciones/eliminar/<int:pk>/", views.eliminar_direccion, name="eliminar_direccion",),
    path("metodos-pago/", views.metodos_pago, name="metodos_pago"),
    path("metodos-pago/agregar/", views.agregar_metodo_pago, name="agregar_metodo_pago"),
    path("metodos-pago/eliminar/<int:pk>/", views.eliminar_metodo_pago, name="eliminar_metodo_pago",),
    path("panel/productos/", views.panel_productos, name="panel_productos"),
    path("panel/productos/crear/", views.panel_crear_producto, name="panel_crear_producto",),
    path("panel/productos/editar/<int:pk>/", views.panel_editar_producto, name="panel_editar_producto",),
    path("panel/productos/eliminar/<int:pk>/", views.panel_eliminar_producto, name="panel_eliminar_producto",),
    path('panel/pedidos/', views.panel_pedidos, name='panel_pedidos'),
    path('panel/pedidos/estado/<int:pk>/', views.panel_cambiar_estado_pedido, name='panel_cambiar_estado_pedido'),
    path('panel/clientes/', views.panel_clientes, name='panel_clientes'),
    path('panel/categorias/', views.panel_categorias, name='panel_categorias'),
    path('panel/categorias/eliminar/<int:pk>/', views.panel_eliminar_categoria, name='panel_eliminar_categoria'),
]
