# Generated by Django 6.0.6 on 2026-06-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnexo', '0004_direccionenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='direccionenvio',
            name='nombre_titular',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccionenvio',
            name='predeterminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='direccionenvio',
            name='tipo',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('paypal', 'PayPal'), ('transferencia', 'Transferencia Bancaria')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccionenvio',
            name='ultimos_digitos',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
