# Generated by Django 6.0.6 on 2026-06-18 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnexo', '0005_metodopago_direccionenvio_nombre_titular_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccionenvio',
            name='nombre_titular',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='predeterminado',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='ultimos_digitos',
        ),
        migrations.AddField(
            model_name='metodopago',
            name='nombre_titular',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metodopago',
            name='predeterminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('paypal', 'PayPal'), ('transferencia', 'Transferencia Bancaria')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metodopago',
            name='ultimos_digitos',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
